# Generated by Django 5.0 on 2024-07-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_censorinfo_movieinfo_poster_movieinfo_censor_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='censor_details',
        ),
        migrations.DeleteModel(
            name='CensorInfo',
        ),
    ]
